<a href="https://colab.research.google.com/github/ds-gowusu/ds-ml-portfolio/blob/main/growth_analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# mount google drive to this notebook
from google.colab import drive

drive.mount('/content/drive')

# connect to the data using pandas dataframe
data = '/content/drive/My Drive/FG_DATA/2021_TAIN_II_DATA.xlsx'

df = pd.read_excel(data, 'PSP TEAK 2021 VI', index_col=None)

df.head()

Mounted at /content/drive


No. Day  Month   Year Planting Year  Measuring moment  \
0    1   3      2   2021          2018                 1   
1    2   3      2   2021          2018                 1   
2    3   3      2   2021          2018                 1   
3    4   3      2   2021          2018                 1   
4    5   3      2   2021          2018                 1   

                    Monitoring  Team Block Plot Number  Slope  ... Fire Scars  \
0  Belinda, Augustine, Kate, Cynaida   A52         865      2  ...         No   
1  Belinda, Augustine, Kate, Cynaida   A52         865      2  ...         No   
2  Belinda, Augustine, Kate, Cynaida   A52         865      2  ...         No   
3  Belinda, Augustine, Kate, Cynaida   A52         865      2  ...         No   
4  Belinda, Augustine, Kate, Cynaida   A52         865      2  ...         No   

  Beetle Erosion Tree Number  Height  DBH       H/D  Remarks Match  Test  
0     No      No         1.0     6.5  6.3  1.031746      NaN   NaN  True  
1     No      No         2.0    6.25  6.6  0.946970      NaN   NaN  True  
2     No      No         3.0    2.75    3  0.916667      NaN   NaN  True  
3     No      No         4.0     5.5  7.3  0.753425      NaN   NaN  True  
4     No      No         5.0    4.25  5.3  0.801887      NaN   NaN  True  

[5 rows x 21 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67797 entries, 0 to 67796
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   No.               67797 non-null  int64  
 1   Day               67797 non-null  object 
 2   Month             67797 non-null  int64  
 3    Year             67797 non-null  int64  
 4   Planting Year     67797 non-null  object 
 5   Measuring moment  67797 non-null  int64  
 6   Monitoring  Team  67797 non-null  object 
 7   Block             67797 non-null  object 
 8   Plot Number       67797 non-null  object 
 9   Slope             67797 non-null  int64  
 10  Diseases          67797 non-null  object 
 11  Fire Scars        67797 non-null  object 
 12  Beetle            67797 non-null  object 
 13  Erosion           67797 non-null  object 
 14  Tree Number       67797 non-null  float64
 15  Height            67797 non-null  object 
 16  DBH               67797 non-null  object

In [4]:
df = df[[' Year', 'Planting Year', 'Block', 'Plot Number', 'Diseases', 'Beetle', 'Tree Number', 'Height', 'DBH', 'Remarks']]
df.head()

Year Planting Year Block Plot Number Diseases Beetle  Tree Number Height  \
0   2021          2018   A52         865       No     No          1.0    6.5   
1   2021          2018   A52         865       No     No          2.0   6.25   
2   2021          2018   A52         865       No     No          3.0   2.75   
3   2021          2018   A52         865       No     No          4.0    5.5   
4   2021          2018   A52         865       No     No          5.0   4.25   

   DBH Remarks  
0  6.3     NaN  
1  6.6     NaN  
2    3     NaN  
3  7.3     NaN  
4  5.3     NaN

In [5]:
df = df[[' Year','Block', 'Planting Year', 'Plot Number', 'Tree Number', 'Height', 'DBH', 'Diseases', 'Beetle', 'Remarks']]
df.head()

Year Block Planting Year Plot Number  Tree Number Height  DBH Diseases  \
0   2021   A52          2018         865          1.0    6.5  6.3       No   
1   2021   A52          2018         865          2.0   6.25  6.6       No   
2   2021   A52          2018         865          3.0   2.75    3       No   
3   2021   A52          2018         865          4.0    5.5  7.3       No   
4   2021   A52          2018         865          5.0   4.25  5.3       No   

  Beetle Remarks  
0     No     NaN  
1     No     NaN  
2     No     NaN  
3     No     NaN  
4     No     NaN

In [6]:
df['Remarks'].unique()

array([nan, 'Top Broken', 'Climber on top', 'Beetle', 'Bent', 'Dieback',
       'Top broken'], dtype=object)

In [7]:
df = df[~((df['Remarks'] == 'Beetle') | (df['Remarks'] == 'Dieback'))]

In [8]:
df.head()

Year Block Planting Year Plot Number  Tree Number Height  DBH Diseases  \
0   2021   A52          2018         865          1.0    6.5  6.3       No   
1   2021   A52          2018         865          2.0   6.25  6.6       No   
2   2021   A52          2018         865          3.0   2.75    3       No   
3   2021   A52          2018         865          4.0    5.5  7.3       No   
4   2021   A52          2018         865          5.0   4.25  5.3       No   

  Beetle Remarks  
0     No     NaN  
1     No     NaN  
2     No     NaN  
3     No     NaN  
4     No     NaN

In [9]:
df['Remarks'].unique()

array([nan, 'Top Broken', 'Climber on top', 'Bent', 'Top broken'],
      dtype=object)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 67787 entries, 0 to 67796
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0    Year          67787 non-null  int64  
 1   Block          67787 non-null  object 
 2   Planting Year  67787 non-null  object 
 3   Plot Number    67787 non-null  object 
 4   Tree Number    67787 non-null  float64
 5   Height         67787 non-null  object 
 6   DBH            67787 non-null  object 
 7   Diseases       67787 non-null  object 
 8   Beetle         67787 non-null  object 
 9   Remarks        240 non-null    object 
dtypes: float64(1), int64(1), object(8)
memory usage: 5.7+ MB


### Compute Age of Trees

In [13]:
df['Planting Year'].unique()

array([2018, 'UNKNOWN', 2017, 2007, 2015, 2014, 2013], dtype=object)

In [14]:
# Replace 'UNKNOWN' with 2000
df['Planting Year'] = df['Planting Year'].replace('UNKNOWN', '2000')

In [15]:
# convert data from str to float numbers
df[' Year'] = df[' Year'].astype(int)
df['Planting Year'] = df['Planting Year'].astype(int)

In [16]:
df['Age'] = df[' Year'] - df['Planting Year']
df.head()

Year Block  Planting Year Plot Number  Tree Number Height  DBH Diseases  \
0   2021   A52           2018         865          1.0    6.5  6.3       No   
1   2021   A52           2018         865          2.0   6.25  6.6       No   
2   2021   A52           2018         865          3.0   2.75    3       No   
3   2021   A52           2018         865          4.0    5.5  7.3       No   
4   2021   A52           2018         865          5.0   4.25  5.3       No   

  Beetle Remarks  Age  
0     No     NaN    3  
1     No     NaN    3  
2     No     NaN    3  
3     No     NaN    3  
4     No     NaN    3

In [17]:
df['Age'].unique()

array([ 3, 21,  4, 14,  6,  7,  8])

### Compute Basal Area of individual Tree

In [23]:
df['DBH'].unique()

array([6.3, 6.6, 3, 7.3, 5.3, 6.5, 5.7, 'dead', 6.4, 7.9, 5.2, 7.5, 6.2,
       4, 7.1, 5, 4.9, 7, 6, 4.2, 8, 8.1, 5.5, 3.6, 5.6, 2, 4.7, 8.5, 6.1,
       3.7, 6.8, 8.3, 2.3, 3.3, 7.2, 6.7, 5.1, 4.8, 5.9, 2.5, 4.6, 3.1,
       4.5, 5.8, 0, 7.7, 6.9, 4.4, 7.4, 3.9, 4.1, 3.5, 3.8, 5.4, 9.3, 8.4,
       8.2, 9, 9.4, 1.3, 8.6, 8.7, 10.2, 10.1, 11, 2.8, 4.3, 3.4, 2.9,
       2.7, 7.8, 2.2, 2.1, 9.9, 9.7, 1.4, 3.2, 1.9, 7.6, 2.4, 9.5, 12.9,
       8.8, 1.5, 8.9, 9.6, 1.6, 11.1, 9.8, 9.1, 11.7, 1.2, 2.6, 1.8, 1.7,
       1.1, 4.75, 3.25, 19, 25, 21, 24, 25.7, 23.8, 16.2, 27.4, 15.4,
       16.5, 17.2, 22, 22.5, 15, 20.5, 23.5, 29, 20.4, 13.7, 16.7, 31.5,
       23.2, 20.3, 29.2, 27.2, 19.3, 23.4, 20.7, 11.6, 22.3, 22.9, 24.7,
       0.9, 1, 9.2, 10.4, 10.7, 10.5, 12.3, 11.4, 12, 10, 10.3, 2.25,
       11.8, 11.3, 10.6, 10.9, 10.8, 13.4, 13.2, 12.4, 14.3, 14.4, 16.9,
       14.2, 15.6, 18.5, 15.7, 13.1, 14.8, 15.2, 12.8, 12.7, 13.3, 13.6,
       18.3, 14, 17.5, 15.5, 11.2, 11.5, 13.9, 12.5, 19

In [24]:
df = df[~((df['DBH'] == 'dead'))]

In [25]:
df['DBH'] = df['DBH'].astype(float)

/tmp/ipython-input-3841508629.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DBH'] = df['DBH'].astype(float)


In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 38842 entries, 0 to 67793
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0    Year          38842 non-null  int64  
 1   Block          38842 non-null  object 
 2   Planting Year  38842 non-null  int64  
 3   Plot Number    38842 non-null  object 
 4   Tree Number    38842 non-null  float64
 5   Height         38842 non-null  object 
 6   DBH            38842 non-null  float64
 7   Diseases       38842 non-null  object 
 8   Beetle         38842 non-null  object 
 9   Remarks        237 non-null    object 
 10  Age            38842 non-null  int64  
dtypes: float64(2), int64(3), object(6)
memory usage: 3.6+ MB


In [32]:
df['Basal_area_m2'] = (np.pi * df['DBH']**2) / 40000


/tmp/ipython-input-214273503.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Basal_area_m2'] = (np.pi * df['DBH']**2) / 40000


In [33]:
df.head()

Year Block  Planting Year Plot Number  Tree Number Height  DBH Diseases  \
0   2021   A52           2018         865          1.0    6.5  6.3       No   
1   2021   A52           2018         865          2.0   6.25  6.6       No   
2   2021   A52           2018         865          3.0   2.75  3.0       No   
3   2021   A52           2018         865          4.0    5.5  7.3       No   
4   2021   A52           2018         865          5.0   4.25  5.3       No   

  Beetle Remarks  Age  Basal_area_m2  
0     No     NaN    3       0.003117  
1     No     NaN    3       0.003421  
2     No     NaN    3       0.000707  
3     No     NaN    3       0.004185  
4     No     NaN    3       0.002206

### Compute Basal Area per Hectare

In [34]:
# Sum basal area per plot
ba_plot = df['Basal_area_m2'].sum()

# convert hectare
plot_area = 0.08 # 800sq.meter
df['basal_area_per_ha'] = ba_plot / plot_area


/tmp/ipython-input-2553713250.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['basal_area_per_ha'] = ba_plot / plot_area


In [35]:
df.head()

Year Block  Planting Year Plot Number  Tree Number Height  DBH Diseases  \
0   2021   A52           2018         865          1.0    6.5  6.3       No   
1   2021   A52           2018         865          2.0   6.25  6.6       No   
2   2021   A52           2018         865          3.0   2.75  3.0       No   
3   2021   A52           2018         865          4.0    5.5  7.3       No   
4   2021   A52           2018         865          5.0   4.25  5.3       No   

  Beetle Remarks  Age  Basal_area_m2  basal_area_per_ha  
0     No     NaN    3       0.003117        6130.121839  
1     No     NaN    3       0.003421        6130.121839  
2     No     NaN    3       0.000707        6130.121839  
3     No     NaN    3       0.004185        6130.121839  
4     No     NaN    3       0.002206        6130.121839

### Compute Volume per Tree

In [36]:
form_factor = 0.45 # replace with the actual form factor constant
df['Volume_per_tree'] = df['Basal_area_m2'] * df['Height'] * form_factor

/tmp/ipython-input-1514428283.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Volume_per_tree'] = df['Basal_area_m2'] * df['Height'] * form_factor


In [37]:
df.head()

Year Block  Planting Year Plot Number  Tree Number Height  DBH Diseases  \
0   2021   A52           2018         865          1.0    6.5  6.3       No   
1   2021   A52           2018         865          2.0   6.25  6.6       No   
2   2021   A52           2018         865          3.0   2.75  3.0       No   
3   2021   A52           2018         865          4.0    5.5  7.3       No   
4   2021   A52           2018         865          5.0   4.25  5.3       No   

  Beetle Remarks  Age  Basal_area_m2  basal_area_per_ha Volume_per_tree  
0     No     NaN    3       0.003117        6130.121839        0.009118  
1     No     NaN    3       0.003421        6130.121839        0.009622  
2     No     NaN    3       0.000707        6130.121839        0.000875  
3     No     NaN    3       0.004185        6130.121839        0.010359  
4     No     NaN    3       0.002206        6130.121839        0.004219

### Compute Volume per hectare

In [38]:
total_volume = df['Volume_per_tree'].sum()

df['Volume_per_ha'] = total_volume / plot_area

/tmp/ipython-input-188810228.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Volume_per_ha'] = total_volume / plot_area


In [39]:
df.head()

Year Block  Planting Year Plot Number  Tree Number Height  DBH Diseases  \
0   2021   A52           2018         865          1.0    6.5  6.3       No   
1   2021   A52           2018         865          2.0   6.25  6.6       No   
2   2021   A52           2018         865          3.0   2.75  3.0       No   
3   2021   A52           2018         865          4.0    5.5  7.3       No   
4   2021   A52           2018         865          5.0   4.25  5.3       No   

  Beetle Remarks  Age  Basal_area_m2  basal_area_per_ha Volume_per_tree  \
0     No     NaN    3       0.003117        6130.121839        0.009118   
1     No     NaN    3       0.003421        6130.121839        0.009622   
2     No     NaN    3       0.000707        6130.121839        0.000875   
3     No     NaN    3       0.004185        6130.121839        0.010359   
4     No     NaN    3       0.002206        6130.121839        0.004219   

   Volume_per_ha  
0   34805.002092  
1   34805.002092  
2   34805.002092  
3   34805.002092  
4   34805.002092